let DATA=null,page=1,pageSize=40;
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat().format(n),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cacheKey='bmc-artwork-v1';
let ART=JSON.parse(localStorage.getItem(cacheKey)||'{}');
const saveArt=()=>localStorage.setItem(cacheKey,JSON.stringify(ART));
function init(){
 const m=DATA.meta,a=DATA.topArtists[0],s=DATA.topSongs[0],al=DATA.topAlbums[0];
 $('heroHours').textContent=m.hours.toFixed(0);$('heroPlays').textContent=fmt(m.plays_total);$('heroDays').textContent=fmt(m.days);
 $('statArtist').textContent=a.Artist;$('statArtistPlays').textContent=fmt(a.Plays)+' plays';$('statSong').textContent=s.Song;$('statSongPlays').textContent=fmt(s.Plays)+' plays';$('statAlbum').textContent=al.Album;$('statAlbumPlays').textContent=fmt(al.Plays)+' plays';
 $('statDaily').textContent=(m.hours*60/(m.days||1)).toFixed(0);
 renderBars();renderArtists();renderAlbums();renderSongs();renderYears();renderMonthly();renderRediscover();renderInsights();renderGenres();hydrateAlbumArt();
 [...new Set(DATA.history.map(x=>x.date.slice(0,4)))].sort().reverse().forEach(y=>$('yearFilter').insertAdjacentHTML('beforeend',`<option>${y}</option>`));
 ['historySearch','yearFilter','endedFilter'].forEach(id=>$(id).addEventListener('input',()=>{page=1;renderHistory()}));
 $('resetFilters').onclick=()=>{$('historySearch').value='';$('yearFilter').value='';$('endedFilter').value='';page=1;renderHistory()};$('prevPage').onclick=()=>{if(page>1){page--;renderHistory()}};$('nextPage').onclick=()=>{page++;renderHistory()};
 $('modalClose').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=closeModal;renderHistory();
}
function artistLink(name){return `<button class="entity-link" data-type="artist" data-key="${esc(name)}">${esc(name)}</button>`}
function songLink(s,a,al){return `<button class="entity-link" data-type="song" data-key="${esc(s)}" data-artist="${esc(a)}" data-album="${esc(al)}">${esc(s)}</button>`}
function albumLink(al,a){return `<button class="entity-link" data-type="album" data-key="${esc(al)}" data-artist="${esc(a)}">${esc(al)}</button>`}
document.addEventListener('click',e=>{const b=e.target.closest('.entity-link');if(b)openEntity(b.dataset.type,b.dataset.key,b.dataset.artist,b.dataset.album)});
function renderBars(){const arr=DATA.topArtists.slice(0,12),max=arr[0].Plays;$('artistBars').innerHTML=arr.map((x,i)=>`<div class="bar-row"><div>${i+1}</div><div><div class="bar-name">${artistLink(x.Artist)}</div><div class="bar-track"><div class="bar-fill" style="width:${x.Plays/max*100}%"></div></div></div><div class="bar-value">${fmt(x.Plays)}</div></div>`).join('')}
function renderArtists(){const q=($('artistSearch').value||'').toLowerCase(),arr=DATA.entities.artists.filter(x=>x.artist.toLowerCase().includes(q)).slice(0,100);$('artistList').innerHTML=arr.map(x=>`<div class="artist-item">${artistLink(x.artist)}<span>${fmt(x.plays)} plays</span></div>`).join('')||'<p class="muted">No artists found.</p>'}
$('artistSearch').addEventListener('input',renderArtists);
function renderAlbums(){const arr=DATA.entities.albums.slice(0,24);$('albumGrid').innerHTML=arr.map(x=>`<button class="album-card entity-link" data-type="album" data-key="${esc(x.album)}" data-artist="${esc(x.artist)}"><div class="art-placeholder">♪</div><div><b>${esc(x.album)}</b><span>${esc(x.artist)}</span><em>${fmt(x.plays)} plays · ${x.hours.toFixed(1)}h</em></div></button>`).join('')}
function renderSongs(){$('songTable').innerHTML=DATA.topSongs.slice(0,75).map(x=>`<tr><td>${x['#']}</td><td><b>${songLink(x.Song,x.Artist,x.Album)}</b></td><td>${artistLink(x.Artist)}</td><td>${albumLink(x.Album,x.Artist)}</td><td>${fmt(x.Plays)}</td><td>${(+x['Hours Listened']).toFixed(1)}</td></tr>`).join('')}
function renderYears(){$('yearCards').innerHTML=DATA.wrapped.filter(x=>x.Year&&x['Top Song']).map(x=>`<button class="year-card entity-link" data-type="year" data-key="${esc(x.Year)}"><div class="year">${esc(x.Year)}${x.Year==2023||x.Year==2026?' · PARTIAL':''}</div><h4>${artistLink(x['Top Artist'])}</h4><p>Top artist · ${fmt(x.Plays)} plays</p><h4>${songLink(x['Top Song'],x['Top Artist'],'')}</h4><p>Top song</p><div class="metric">${(+x.Hours).toFixed(0)}<small> hours</small></div><p>${fmt(x.Songs)} song plays represented</p></button>`).join('')}
function renderMonthly(){const arr=DATA.monthly.slice().reverse(),max=Math.max(...arr.map(x=>+x.Plays||0));$('monthlyChart').innerHTML=arr.map(x=>{let d=new Date(x.Month),lab=d.toLocaleDateString(undefined,{month:'short',year:'2-digit'});return `<div class="month-bar-wrap"><div class="month-tip">${lab}: ${fmt(x.Plays)} plays · ${(+x.Hours).toFixed(1)}h<br>${esc(x['Top Artist'])}</div><div class="month-bar" style="height:${Math.max(1,x.Plays/max*225)}px"></div><div class="month-label">${lab}</div></div>`}).join('')}
function renderRediscover(){$('rediscoverTable').innerHTML=DATA.rediscover.filter(x=>x.Song).slice(0,60).map(x=>`<tr><td>${x['#']}</td><td><b>${songLink(x.Song,x.Artist,x.Album)}</b></td><td>${artistLink(x.Artist)}</td><td>${albumLink(x.Album,x.Artist)}</td><td>${fmt(x.Plays)}</td><td>${esc(x['Last Played'])}</td><td>${fmt(x['Days Since'])}</td></tr>`).join('')}
async function renderGenres(){
 const cacheKey='bmc-genres-v1'; let gc=JSON.parse(localStorage.getItem(cacheKey)||'{}');
 const top=DATA.entities.artists.slice(0,80); let done=0;
 const lookup=async a=>{if(gc[a.artist])return gc[a.artist];try{const r=await fetch('https://itunes.apple.com/search?term='+encodeURIComponent(a.artist)+'&entity=musicArtist&limit=3&country=US');const j=await r.json();const hit=j.results?.find(x=>x.primaryGenreName);gc[a.artist]=hit?.primaryGenreName||'Other';localStorage.setItem(cacheKey,JSON.stringify(gc));return gc[a.artist]}catch(e){return null}};
 const results=[];for(let i=0;i<top.length;i+=8){const batch=await Promise.all(top.slice(i,i+8).map(async a=>[a,await lookup(a)]));results.push(...batch);done+=batch.length;if(done>=24){renderGenreResults(results.filter(x=>x[1]));break}}
}
function renderGenreResults(results){const totals={};results.forEach(([a,g])=>totals[g]=(totals[g]||0)+a.plays);const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]).slice(0,10),max=rows[0]?.[1]||1;$('genreList').innerHTML=rows.map(x=>`<div class="bar-row"><div></div><div><div class="bar-name">${esc(x[0])}</div><div class="bar-track"><div class="bar-fill" style="width:${x[1]/max*100}%"></div></div></div><div class="bar-value">${fmt(x[1])}</div></div>`).join('');const heavy=Object.entries(totals).filter(x=>/metal|hardcore|punk|rock|alternative/i.test(x[0])).reduce((a,x)=>a+x[1],0),hip=Object.entries(totals).filter(x=>/hip.?hop|rap/i.test(x[0])).reduce((a,x)=>a+x[1],0);$('genreCompare').innerHTML=`<div class="genre-big"><span>HEAVY / ROCK FAMILY</span><b>${fmt(heavy)}</b><em>plays represented by enriched artists</em></div><div class="genre-big"><span>HIP-HOP / RAP FAMILY</span><b>${fmt(hip)}</b><em>plays represented by enriched artists</em></div><p class="muted">This is a directional lens, not a definitive genre classification of every play.</p>`}
async function hydrateAlbumArt(){const cards=[...document.querySelectorAll('.album-card')];for(const c of cards){const url=await getArt(c.dataset.key,'album');if(url){const ph=c.querySelector('.art-placeholder');if(ph)ph.outerHTML=`<img class="album-art" src="${url}" alt="">`}}}
function renderInsights(){const i=DATA.insights,ls=i.longest_session;$('insightGrid').innerHTML=`<div class="insight"><span>BIGGEST SINGLE DAY</span><b>${fmt(i.most_played_day.plays)} plays</b><p>${i.most_played_day.date} · ${i.most_played_day.artists} artists</p></div><div class="insight"><span>MOST MUSICAL WHIPLASH</span><b>${i.most_varied_day.artists} artists</b><p>${i.most_varied_day.date} · ${fmt(i.most_varied_day.plays)} plays</p></div><div class="insight"><span>LONGEST SESSION</span><b>${ls.minutes.toFixed(0)} min</b><p>${ls.plays} consecutive counted plays</p></div><div class="insight"><span>SONG CATALOG</span><b>${fmt(DATA.entities.songs.length)}</b><p>unique song / artist / album records</p></div>`;
 $('discoveryList').innerHTML=i.discoveries.slice(0,12).map(x=>`<div class="rank-item">${artistLink(x[1])}<span>${x[0]} plays in first 30 days</span></div>`).join('');
 $('skipList').innerHTML=i.skip_rates.slice(0,12).map(x=>`<div class="rank-item">${songLink(x[3][0],x[3][1],x[3][2])}<span>${(x[0]*100).toFixed(0)}% skip rate · ${x[1]} plays</span></div>`).join('');
 $('catalogList').innerHTML=DATA.entities.artists.slice().sort((a,b)=>b.unique_songs-a.unique_songs).slice(0,12).map(x=>`<div class="rank-item">${artistLink(x.artist)}<span>${x.unique_songs} unique songs · ${fmt(x.plays)} plays</span></div>`).join('');
 $('finishList').innerHTML=DATA.insights.skip_rates.slice().sort((a,b)=>{const ar=1-a[0],br=1-b[0];return br-ar}).slice(0,12).map(x=>`<div class="rank-item">${songLink(x[3][0],x[3][1],x[3][2])}<span>${((1-x[0])*100).toFixed(0)}% not-skipped · ${x[1]} plays</span></div>`).join('');
 $('oneHitList').innerHTML=i.one_hit_artists.slice(0,12).map(x=>`<div class="rank-item">${artistLink(x[1])}<span>${x[0]} plays of “${esc(x[2])}”</span></div>`).join('');
 const byA={};DATA.history.forEach(x=>{if(!x.counted)return;const m=x.date.slice(0,7);(byA[x.artist]??= {})[m]=(byA[x.artist]?.[m]||0)+1});const comebacks=[];for(const [a,ms] of Object.entries(byA)){const peaks=Object.entries(ms).sort((x,y)=>y[1]-x[1]);if(peaks.length>1){const last=DATA.history.filter(x=>x.artist===a&&x.counted).at(-1)?.date.slice(0,7);if(last)comebacks.push([peaks[0][1],a,last,peaks[0][0]])}}comebacks.sort((a,b)=>b[0]-a[0]);$('comebackList').innerHTML=comebacks.slice(0,12).map(x=>`<div class="rank-item">${artistLink(x[1])}<span>peak ${fmt(x[0])} plays in ${x[3]} · last active ${x[2]}</span></div>`).join('');const total=Object.values(i.ending_counts).reduce((a,b)=>a+b,0);$('endingList').innerHTML=Object.entries(i.ending_counts).sort((a,b)=>b[1]-a[1]).map(x=>`<div class="ending"><span>${esc(x[0])}</span><div><i style="width:${x[1]/total*100}%"></i></div><b>${(x[1]/total*100).toFixed(1)}%</b></div>`).join('')}
function filteredHistory(){const q=($('historySearch').value||'').toLowerCase(),y=$('yearFilter').value,e=$('endedFilter').value;return DATA.history.filter(x=>(!q||[x.song,x.artist,x.album].some(v=>v.toLowerCase().includes(q)))&&(!y||x.date.startsWith(y))&&(!e||x.ended===e))}
function renderHistory(){const arr=filteredHistory(),pages=Math.max(1,Math.ceil(arr.length/pageSize));if(page>pages)page=pages;const view=arr.slice((page-1)*pageSize,page*pageSize);$('historyCount').textContent=`${fmt(arr.length)} matching plays`;$('historyTable').innerHTML=view.map(x=>`<tr><td>${x.date}</td><td>${x.time}</td><td><b>${songLink(x.song,x.artist,x.album)}</b></td><td>${artistLink(x.artist)}</td><td>${albumLink(x.album,x.artist)}</td><td>${Math.floor(x.listened/60)}:${String(Math.floor(x.listened%60)).padStart(2,'0')}</td><td>${esc(x.ended)}</td></tr>`).join('')||'<tr><td colspan="7">No matches.</td></tr>';$('pageInfo').textContent=`Page ${page} / ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages}
function closeModal(){$('modal').classList.remove('open');$('modal').setAttribute('aria-hidden','true')}
async function getArt(term,entity='album'){const key=entity+'|'+term;if(ART[key])return ART[key];try{const url='https://itunes.apple.com/search?term='+encodeURIComponent(term)+'&entity='+entity+'&limit=8&country=US';const r=await fetch(url);const j=await r.json();const hit=j.results?.find(x=>x.artworkUrl100);if(hit){const u=hit.artworkUrl100.replace('100x100','600x600');ART[key]=u;saveArt();return u}}catch(e){}return ''}
async function openEntity(type,key,artist,album){$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false');$('modalContent').innerHTML='<div class="loading">Loading archive…</div>';if(type==='year'){return openYear(key)}
 if(type==='artist'){const a=DATA.entities.artists.find(x=>x.artist===key);const songs=DATA.entities.songs.filter(x=>x.artist===key).slice(0,30),months=DATA.history.filter(x=>x.artist===key).reduce((o,x)=>(o[x.date.slice(0,7)]=(o[x.date.slice(0,7)]||0)+1,o),{});const topMonth=Object.entries(months).sort((a,b)=>b[1]-a[1])[0];const art=await getArt(songs[0]?.album||key,'album');$('modalContent').innerHTML=profileHeader(art,key,a?`${fmt(a.plays)} plays · ${a.hours.toFixed(1)} hours · ${a.unique_songs} unique songs`:'' )+artistListenLinks(key)+`<div class="detail-grid"><div><span>PEAK MONTH</span><b>${topMonth?topMonth[0]:'—'}</b><p>${topMonth?fmt(topMonth[1])+' plays':''}</p></div><div><span>FIRST PLAY</span><b>${firstFor('artist',key)}</b></div><div><span>LAST PLAY</span><b>${lastFor('artist',key)}</b></div></div><h4>Top tracks</h4><div class="detail-list">${songs.map((x,i)=>`<div>${i+1}. ${songLink(x.song,x.artist,x.album)}<span>${fmt(x.plays)} plays</span></div>`).join('')}</div>`}
 if(type==='album'){const a=DATA.entities.albums.find(x=>x.album===key&&x.artist===artist)||DATA.entities.albums.find(x=>x.album===key);const songs=DATA.entities.songs.filter(x=>x.album===key&&(!artist||x.artist===artist));const art=await getArt(key,'album');$('modalContent').innerHTML=profileHeader(art,key,a?`${artist||a.artist} · ${fmt(a.plays)} plays · ${a.hours.toFixed(1)} hours`:artist||'')+`<h4>Tracks in the archive</h4><div class="detail-list">${songs.map((x,i)=>`<div>${i+1}. ${songLink(x.song,x.artist,x.album)}<span>${fmt(x.plays)} plays</span></div>`).join('')}</div>`;return}
 if(type==='song'){const matches=DATA.history.filter(x=>x.song===key&&(!artist||x.artist===artist));const a=DATA.entities.songs.find(x=>x.song===key&&(!artist||x.artist===artist));const art=await getArt(album||a?.album||key,'album');const ends={};matches.forEach(x=>ends[x.ended]=(ends[x.ended]||0)+1);const rate=matches.length?((ends['Skipped forward']||0)+(ends['Switched to another song']||0))/matches.length:0;$('modalContent').innerHTML=profileHeader(art,key,a?`${a.artist} · ${a.album}`:'')+listenLinks(key,artist||a?.artist,album||a?.album)+`<div class="detail-grid"><div><span>PLAYS</span><b>${fmt(matches.length)}</b></div><div><span>LISTENING</span><b>${a?a.hours.toFixed(1):'—'} h</b></div><div><span>SKIP RATE</span><b>${(rate*100).toFixed(1)}%</b></div></div><h4>Recent listens</h4><div class="detail-list">${matches.slice(0,25).map(x=>`<div>${x.date} ${x.time}<span>${esc(x.ended)}</span></div>`).join('')}</div>`}}
function artistListenLinks(artist){
 const q=encodeURIComponent(artist);
 return `<div class="listen-box"><div class="panel-title">LISTEN TO THIS ARTIST</div><div class="listen-links">
 <a class="listen-btn spotify" href="https://open.spotify.com/search/${q}" target="_blank" rel="noopener noreferrer"><b>Spotify</b><span>Search artist</span></a>
 <a class="listen-btn youtube" href="https://www.youtube.com/results?search_query=${q}" target="_blank" rel="noopener noreferrer"><b>YouTube</b><span>Search artist</span></a>
 <a class="listen-btn bandcamp" href="https://bandcamp.com/search?q=${q}" target="_blank" rel="noopener noreferrer"><b>Bandcamp</b><span>Search artist</span></a>
 <a class="listen-btn apple" href="https://music.apple.com/us/search?term=${q}" target="_blank" rel="noopener noreferrer"><b>Apple Music</b><span>Open catalog</span></a>
 <a class="listen-btn soundcloud" href="https://soundcloud.com/search?q=${q}" target="_blank" rel="noopener noreferrer"><b>SoundCloud</b><span>Search artist</span></a>
 </div><p class="listen-note">These use each service's search, which keeps the archive useful for obscure and independent artists too.</p></div>`
}
function listenLinks(song,artist,album){
 const q=encodeURIComponent(`${song} ${artist}`);
 const qa=encodeURIComponent(`${artist} ${album||''}`);
 return `<div class="listen-box"><div class="panel-title">LISTEN TO THIS SONG</div><div class="listen-links">
 <a class="listen-btn spotify" href="https://open.spotify.com/search/${q}" target="_blank" rel="noopener noreferrer"><b>Spotify</b><span>Search track</span></a>
 <a class="listen-btn youtube" href="https://www.youtube.com/results?search_query=${q}" target="_blank" rel="noopener noreferrer"><b>YouTube</b><span>Search video</span></a>
 <a class="listen-btn bandcamp" href="https://bandcamp.com/search?q=${q}" target="_blank" rel="noopener noreferrer"><b>Bandcamp</b><span>Search release</span></a>
 <a class="listen-btn apple" href="https://music.apple.com/us/search?term=${q}" target="_blank" rel="noopener noreferrer"><b>Apple Music</b><span>Open catalog</span></a>
 <a class="listen-btn soundcloud" href="https://soundcloud.com/search?q=${q}" target="_blank" rel="noopener noreferrer"><b>SoundCloud</b><span>Search track</span></a>
 </div><p class="listen-note">These use each service's search, so they also work for obscure or independently released tracks without requiring me to maintain thousands of fragile direct links.</p></div>`
}
function profileHeader(art,title,sub){return `<div class="profile-head">${art?`<img src="${art}" alt="">`:'<div class="art-placeholder large">♪</div>'}<div><div class="eyebrow">ARCHIVE PROFILE</div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div></div>`}
function firstFor(t,k){const x=DATA.history.find(x=>x[t==='artist'?'artist':'song']===k);return x?x.date:'—'}function lastFor(t,k){const x=[...DATA.history].reverse().find(x=>x[t==='artist'?'artist':'song']===k);return x?x.date:'—'}
function openYear(y){const rows=DATA.wrapped.filter(x=>String(x.Year)===String(y));const x=rows[0];$('modalContent').innerHTML=`<div class="profile-head"><div class="art-placeholder large">${esc(y)}</div><div><div class="eyebrow">YEAR IN REVIEW</div><h2>${esc(y)}</h2><p>${x?fmt(x.Plays)+' plays · '+(+x.Hours).toFixed(1)+' hours':''}</p></div></div>${x?`<div class="detail-grid"><div><span>TOP ARTIST</span><b>${esc(x['Top Artist'])}</b><p>${fmt(x.Plays)} plays</p></div><div><span>TOP SONG</span><b>${esc(x['Top Song'])}</b></div><div><span>SONG PLAYS</span><b>${fmt(x.Songs)}</b></div></div>`:''}`}
fetch('data.json').then(r=>r.json()).then(d=>{DATA=d;init()}).catch(e=>{document.body.innerHTML='<main style="padding:50px;font-family:system-ui"><h1>Could not load the music archive.</h1><p>Open this site through a local web server or deploy the folder to a static host.</p></main>'});
