'use strict';
let DATA;
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('en-US').format(n),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).trim().toLowerCase();
const states=Object.fromEntries(['artists','albums','songs','catalog'].map(k=>[k,{page:1,sort:k==='catalog'?'artist':'plays',descending:k!=='catalog'}]));
const size=25;
function entity(type,key,artist='',album=''){return `<button class="entity" data-type="${type}" data-key="${esc(key)}" data-artist="${esc(artist)}" data-album="${esc(album)}">${esc(key)}</button>`}
function getRows(k){const q=norm($(k+'Search').value),s=states[k];return DATA[k].filter(x=>!q||[x.song,x.artist,x.album].filter(Boolean).some(v=>norm(v).includes(q))).slice().sort((a,b)=>{const av=a[s.sort],bv=b[s.sort];const cmp=typeof av==='number'?av-bv:String(av).localeCompare(String(bv));return (s.descending?-cmp:cmp)||String(a.artist).localeCompare(String(b.artist))||String(a.song||a.album||'').localeCompare(String(b.song||b.album||''))})}
function render(k){const rows=getRows(k),s=states[k],pages=Math.max(1,Math.ceil(rows.length/size));s.page=Math.min(s.page,pages);$(k+'Count').textContent=`${fmt(rows.length)} ${k==='catalog'?'unique songs':k}`;
 $(k+'Rows').innerHTML=rows.slice((s.page-1)*size,s.page*size).map(x=>{
 const a=entity('artist',x.artist),al=entity('album',x.album,x.artist),song=entity('song',x.song,x.artist,x.album),rank=`<td class="number">${x.rank}</td>`,plays=`<td class="number">${fmt(x.plays)}</td>`;
 return '<tr>'+(k==='artists'?rank+`<td>${a}</td>`+plays:k==='albums'?rank+`<td>${al}</td><td>${a}</td>`+plays:k==='songs'?rank+`<td>${song}</td><td>${a}</td><td>${al}</td>`+plays:`<td>${song}</td><td>${al}</td><td>${a}</td>` )+'</tr>';
 }).join('')||`<tr><td colspan="5">No matching entries.</td></tr>`;
 $(k+'Pager').innerHTML=`<button data-page="${k}" data-step="-1" ${s.page===1?'disabled':''}>Previous</button><span>Page ${s.page} of ${pages}</span><button data-page="${k}" data-step="1" ${s.page===pages?'disabled':''}>Next</button>`;
 document.querySelectorAll(`[data-table="${k}"]`).forEach(b=>{const active=s.sort===b.dataset.sort;b.parentElement.setAttribute('aria-sort',active?(s.descending?'descending':'ascending'):'none')});
}
function listenLinks(term){const q=encodeURIComponent(term);return `<div class="links"><a href="https://open.spotify.com/search/${q}" target="_blank" rel="noopener noreferrer">Spotify</a><a href="https://www.youtube.com/results?search_query=${q}" target="_blank" rel="noopener noreferrer">YouTube</a><a href="https://bandcamp.com/search?q=${q}" target="_blank" rel="noopener noreferrer">Bandcamp</a><a href="https://music.apple.com/us/search?term=${q}" target="_blank" rel="noopener noreferrer">Apple Music</a><a href="https://soundcloud.com/search?q=${q}" target="_blank" rel="noopener noreferrer">SoundCloud</a></div>`}
function tracksTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Song</th><th>Album</th><th class="number">Plays</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${entity('song',x.song,x.artist,x.album)}</td><td>${entity('album',x.album,x.artist)}</td><td class="number">${fmt(x.plays)}</td></tr>`).join('')||'<tr><td colspan="3">No counted plays.</td></tr>'}</tbody></table></div>`}
function openProfile(type,key,artist,album){let html='';
 if(type==='artist'){const a=DATA.artists.find(x=>norm(x.artist)===norm(key));const rows=DATA.songs.filter(x=>norm(x.artist)===norm(key));html=`<h2>${esc(key)}</h2><p>${a?fmt(a.plays)+' counted plays':''}</p>`+listenLinks(key)+'<h3>Most listened to songs</h3>'+tracksTable(rows)}
 if(type==='album'){const a=DATA.albums.find(x=>norm(x.album)===norm(key)&&norm(x.artist)===norm(artist));const rows=DATA.catalog.filter(x=>norm(x.album)===norm(key)&&norm(x.artist)===norm(artist));html=`<h2>${esc(key)}</h2><p>${entity('artist',artist)}${a?' · '+fmt(a.plays)+' counted plays':''}</p>`+listenLinks(`${artist} ${key}`)+`<h3>Songs in the archive</h3><ul>${rows.map(x=>`<li>${entity('song',x.song,x.artist,x.album)}</li>`).join('')}</ul>`}
 if(type==='song'){const a=DATA.songs.find(x=>norm(x.song)===norm(key)&&norm(x.artist)===norm(artist));html=`<h2>${esc(key)}</h2><p>Artist: ${entity('artist',artist)}</p><p>Album: ${entity('album',album,artist)}</p>${a?`<p>${fmt(a.plays)} counted plays</p>`:''}<h3>Listen</h3>`+listenLinks(`${artist} ${key}`)}
 $('profileContent').innerHTML=html;if(!$('profile').open)$('profile').showModal();
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.type)openProfile(b.dataset.type,b.dataset.key,b.dataset.artist,b.dataset.album);if(b.dataset.sort){const k=b.dataset.table,s=states[k];s.descending=s.sort===b.dataset.sort?!s.descending:b.dataset.sort==='plays';s.sort=b.dataset.sort;s.page=1;render(k)}if(b.dataset.page){states[b.dataset.page].page+=Number(b.dataset.step);render(b.dataset.page)}});
$('closeProfile').onclick=()=>$('profile').close();
fetch('data.json').then(r=>{if(!r.ok)throw new Error('Data request failed');return r.json()}).then(d=>{DATA=d;for(const k of Object.keys(states)){if(k!=='catalog')DATA[k].forEach((x,i)=>x.rank=i+1);$(k+'Search').addEventListener('input',()=>{states[k].page=1;render(k)});render(k)}$('summary').textContent=`${fmt(DATA.artists.length)} artists · ${fmt(DATA.albums.length)} albums · ${fmt(DATA.catalog.length)} unique songs. Rankings count plays of 30 seconds or longer.`}).catch(()=>{$('loadError').hidden=false});
